platform :ios, "7.1"
workspace "ProximitySense Campaign Demo"
inhibit_all_warnings!

target "ProximitySense Campaign Demo" do
    #    pod 'ProximitySenseSDK'
    pod 'MBProgressHUD', '~> 0.8'
    pod 'ZLSwipeableView'

    xcodeproj "ProximitySense Campaign Demo.xcodeproj"
end
