# Uncomment this line to define a global platform for your project
platform :ios, "7.1"
workspace "Campaign Demo"
inhibit_all_warnings!

target "Campaign Demo" do
    pod 'ISO8601DateFormatter', '~> 0.6'
    pod 'InAppSettingsKit', '~> 2.2'

    xcodeproj "Campaign Demo.xcodeproj"
end
